### ISSUE TITLE
Bug: Unable to dismiss Welcome dialog

### ISSUE THREAD

**Issue by NWPerry** [nilsschmidt1337/ldparteditor#734] opened 2019-10-25 16:00 UTC
When launching the program, after filling out all fields in the Welcome dialog, I cannot dismiss the window. The window advises "Setup is complete, press O[K]", but the OK button is greyed out. (Enter/return also doesn't work.)
<img width="521" alt="Screen Shot 2019-10-25 at 11 48 57 AM" src="https://user-images.githubusercontent.com/56901853/67586164-fd2a5400-f71e-11e9-932e-20d3c2dab053.png">

**Comment by nilsschmidt1337** [comment] 2019-11-04 17:58
Hi @NWPerry ,

please move your part authoring folder to your home directory. Then try to extract a recent LDPartEditor release in a sub-folder of your home directory and start the application from there. I think the updated script has messed up your installation.
In case that this solves the problem then you can empty the folder /Applications/LDPartEditor_mac_x64 and replace it with the directory from the home folder and see if you can start LDPartEditor from within /Applications/LDPartEditor_mac_x64.

Unfortunately, I don't run into user interface problems on my MacBook and this is the only device I can use for testing purposes. I do not see any issue in the sourcecode either. But it is suspicious, that the label "Setup is complete, press OK." is not fully visible on your screenshot and the button is still grayed out. There is something wrong with the user interface components (buttons, lables) and its setup. I don't think that the issue is related to some settings in your operating system.

Cheers,
Nils

It could be a file permission problem, too. I am not sure if LDPartEditor is able to read/write to /Applications/Bricksmith/ldraw. But then again you said that you were able to launch an older version...

**Comment by NWPerry** [comment] 2019-11-06 04:46
So I've moved everything into my home user folder—including the parts authoring and LDraw folders as well as the application itself—and the same error occurs.
<img width="565" alt="Screen Shot 2019-11-05 at 11 36 41 PM" src="https://user-images.githubusercontent.com/56901853/68268738-60708c00-0025-11ea-9366-83901381bc0a.png">

Also, the following message appears in my Terminal:
`objc[629]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8f23b3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x179b86f50). One of the two will be used. Which one is undefined.`

I'm actually not sure whether I've ever successfully launched the program, but if so, it was some months ago and I don't remember which version it would have been. The most recent version for which I can get past the welcome dialog is 0.8.44b. But I only get as far as the LDPE splash screen before the program crashes and the following appears in my Terminal:
```
objc[783]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8f23b3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1741e4f50). One of the two will be used. Which one is undefined.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.system.MemoryAccess (file:/Users/nwperry/Desktop/LDPartEditor_mac_x64/LDPartEditor.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of org.lwjgl.system.MemoryAccess
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by nilsschmidt1337** [comment] 2019-11-08 16:01
Is there an _error_log.txt_ file in the LDPE application folder? If yes, would it be possible to post its contents here in case that it contains more information about the issue?

**Comment by NWPerry** [comment] 2019-11-08 18:56
Yes, here it is: [error_log.txt](https://github.com/nilsschmidt1337/ldparteditor/files/3825846/error_log.txt)

**Comment by NWPerry** [comment] 2019-11-08 18:58
And here is the one generated by version 0.8.44b: [error_log.txt](https://github.com/nilsschmidt1337/ldparteditor/files/3825851/error_log.txt)

**Comment by billthefish** [comment] 2020-01-08 23:58
For what it's worth, I'm experience the exact same problem.
I have macOS Catalina 10.15.2 and JDK 13.0.1 x64 installed
Also, LDPE does not appear to play well when Dark Mode is enabled.

**Comment by NWPerry** [comment] 2020-01-09 00:43
I can happily report that the latest version (I guess it's 0.8.50?) does not have this issue. The button lights up once I completely fill out the form, and the program launches fully!

**Comment by nilsschmidt1337** [comment] 2020-05-18 17:23
Thanks, I will close this now

**Closed by nilsschmidt1337** 2020-05-18 17:23 UTC
Labels: bug, support
